### ISSUE TITLE
Add command line tool for displaying table of SPI flash modules supported

### ISSUE THREAD

**Issue by mithro** [litex-hub/litespi#11]

**Comment by mithro** [comment]
Example at https://github.com/mithro/litex/blob/d7184b97494012a8c21ee93df231b758a61e9dec/litex/soc/cores/spi/modules.py#L901-L909

**Comment by kowalewskijan** [comment]
This is done ([link](https://github.com/litex-hub/litespi/pull/1/files#diff-df41fe3aa0d9e2aeb6bb909f44e97af9R5-R13))
