### ISSUE TITLE
Import size cross-checking Python code

### ISSUE THREAD

**Issue by mithro** [litex-hub/litespi#12]
My original Python code cross checked that the total size / page size / page count values all cross checked together.

See https://github.com/mithro/litex/blob/spi-module/litex/soc/cores/spi/modules.py#L22-L137

**Comment by kowalewskijan** [comment]
This is done ([link](https://github.com/litex-hub/litespi/pull/1/files#diff-df41fe3aa0d9e2aeb6bb909f44e97af9R5-R13))
