### ISSUE TITLE
Import enums from Mithro's old work

### ISSUE THREAD

**Issue by mithro** [litex-hub/litespi#3]
https://github.com/mithro/litex/tree/spi-module/litex/soc/cores/spi

 - https://github.com/mithro/litex/blob/spi-module/litex/soc/cores/spi/ids.py
 - https://github.com/mithro/litex/blob/spi-module/litex/soc/cores/spi/opcodes.py
 - https://github.com/mithro/litex/blob/spi-module/litex/soc/cores/spi/protocol.py

And anything else in that repository.

**Comment by kowalewskijan** [comment]
This is done in PR: [link](https://github.com/litex-hub/litespi/pull/1)
